port: 5000
tezos:
  tezos_client: tezos-bin/amd64/tezos-client
  dir: tezos-bin
  default_protocol: ProtoALphaALphaALphaALphaALphaALphaALphaALphaDdp3zK
  reveal_fee: 1000
  originator: "bootstrap2"
log:
  location: tezos-sc-tester.log
  level: debug
