FROM arm64v8/alpine:3.15.4

# Create application directory
RUN mkdir -p /opt/tezos

ADD ./tezos-bin/arm64/tezos-client  /opt/tezos/tezos-client
ADD ./bin/linux_arm64/api           /opt/tezos/tezos-testing
ADD ./docker/config.yaml            /opt/tezos/config.yaml

EXPOSE 5000/tcp

ENTRYPOINT ["/opt/tezos/tezos-testing", "-config=/opt/tezos/config.yaml"]
