basePath: /
definitions:
  action.Action:
    properties:
      kind:
        type: string
      payload:
        items:
          type: integer
        type: array
    type: object
  action.ActionResult:
    properties:
      action: {}
      result: {}
      status:
        type: string
    type: object
  api.testSuiteRequest:
    properties:
      actions:
        items:
          $ref: '#/definitions/action.Action'
        type: array
      protocol:
        type: string
    type: object
  error.Error:
    properties:
      code:
        example: 409
        type: integer
      details: {}
      message:
        example: Some Error
        type: string
    type: object
info:
  contact: {}
  description: API documentation
  title: Visualtez Testing API
  version: "1.0"
paths:
  /testing:
    post:
      consumes:
      - application/json
      operationId: post-testing
      parameters:
      - description: Test Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.testSuiteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            items:
              $ref: '#/definitions/action.ActionResult'
            type: array
        "409":
          description: Fail
          schema:
            $ref: '#/definitions/error.Error'
      summary: Run a test
swagger: "2.0"
