name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version:
          - 1.18

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Download dependencies
        run: make

      - name: Check dependencies checksum
        run: git diff --quiet go.sum

      - name: Build executables
        run: make all-build

      - name: Run tests
        run: make test
